### PR TITLE
+malanime: Better debugging and fix when parsing animes with "unknown" episodes

### PR DESCRIPTION
**Pull request by Nightdavisao**
* implements exceptions to better debugging (better understanding of what gone wrong)
* fixes command error when parsing animes with "unknown" episodes
* better logging
* query scrapping: now it uses regular expressions to make sure that we got the right page to parse

### CODE REVIEW

**Comment by Nightdavisao** [comment]
thank you eevee aka xgabriel for reviewing my PR .

**Comment by Nightdavisao** [comment]
cute xgabriel

**Comment by xGabrielDEV** [comment]
This is not professional, the project is serious. Please review your behavior.

**Comment by Nightdavisao** [comment]
^ deleted the comment regarding of my unprofessional comments that i deleted too
sorry for that

**Pull request merged**
