### PR TITLE
Migrate remindme commands to new locale

### PR DESCRIPTION
**Pull request by bit-man**

### CODE REVIEW

**Review by SrGaabriel — APPROVED** [review]

**Comment by MrPowerGamerBR** [comment]
Would be nicer if the locale keys are in `camelCase`

**Comment by bit-man** [comment]
@MrPowerGamerBR  anything else that I can do to make this PR approved or merged?

**Comment by SrGaabriel** [comment]
Includes https://github.com/LorittaBot/LorittaLocales/pull/100.

**Comment by bit-man** [comment]
Please, let me know if there'a anything that needs to be changed or fixed for this PR to advance

**Comment by bit-man** [comment]
Sorry @SrGaabriel @MrPowerGamerBR  to bother you again but I can't see this PR counting for Hacktoborfest. Could you approve it, please, or let me know how to advance to approval o merge?

**Comment by bit-man** [comment]
Thanks!

**Pull request merged**
