### PR TITLE
Added more aliases to +aboutme command.

### PR DESCRIPTION
**Pull request by Sazzo**
New Aliases:
- +bio
- +biography

Changes or suggestions will be appreciated if something is wrong (:

### CODE REVIEW

**Comment by Sazzo** [comment]
oh no the check failed, i think it is nothing related to my pull request so for now, i will just ignore it.

**Comment by MrPowerGamerBR** [comment]
Needs to be rebased due to conflicts

**Comment by Sazzo** [comment]
Should be okay now (:

**Comment by Sazzo** [comment]
Closing this since it's not really useful anymore.

**Pull request closed without merging**
