### PR TITLE
Update BanInfoCommand.kt

### PR DESCRIPTION
**Pull request by iiAmFilippi**
I fixed the baninfo command that returned null where it was supposed to be the reason for the ban if the ban had no reason.

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
But when the reason is null?

**Comment by iiAmFilippi** [comment]
> 
> 
> But when the reason is null?

When the ban has no reason

**Comment by SrGaabriel** [comment]
@iiAmFilippi The punishment reason is actually **empty** when there's no specified reason.

But you can still do something like this:

```kotlin
val reason = banInformation.reason.ifEmpty { "No reason specified." }
```

And remember, the reason is only empty if the punishment was not made with Loritta and there's not reason specified, so that's a really rare case.

**Comment by MrPowerGamerBR** [comment]
And if this is added, the "No reason specified" should be added to Loritta's locales

**Pull request closed without merging**
