### PR TITLE
Another attempt to migrate locale

### PR DESCRIPTION
**Pull request by Lucasmellof**
Related to #2264.

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
Looks great!

**Comment by MrPowerGamerBR** [comment]
@Lucasmellof some changes that I would like, to make the locale file a bit better:

https://github.com/LorittaBot/LorittaLocales/pull/113/files#diff-a385561652b4936eb6706c141c56142ee15860e8cc99172cdd5d60bac07f4f03R67

Instead of using `\n`, please use a list to make it easier to be edited in the future, example:
```
    blacklisted: "Eu me recuso a ficar neste servidor! ᕙ(⇀‸↼‶)ᕗ\n\n**Motivo:** {0}\n\nSe você acha que o ban foi injusto (duvido que foi injusto) ou se você se arrependeu, envie uma mensagem privada para `MrPowerGamerBR#4185` pedindo para ser desbanido!\n\nDesculpe pela inconveniência..." 
```

```yaml
    blacklisted: 
    - "Eu me recuso a ficar neste servidor! ᕙ(⇀‸↼‶)ᕗ"
    - ""
    - "**Motivo:** {0}"
    - ""
    - "Se você acha que o ban foi injusto (duvido que foi injusto) ou se você se arrependeu, envie uma mensagem privada para `MrPowerGamerBR#4185` pedindo para ser desbanido!"
    - ""
    - "Desculpe pela inconveniência..."
```

Then, in the code, you can use `locale.getList("locale.key.here").joinToString("\n")`

Strings that should be changed to use a list:
`blacklisted`
`ownerLorittaBanned`
`addedOnServer`
`nicknameChanged`
`messageEdited`
`inviteInfo`

Aside from that issue, I think it looks great! (But for some reason the `addedOnServer` key is invalid because of the unicode emojis, but I guess that won't be an issue, but if it is I can remove the emojis myself)

Thanks! 😊

**Comment by Lucasmellof** [comment]
I will make these changes and commit again.

**Comment by Lucasmellof** [comment]
Is everything correct or i need to make more changes?

**Comment by MrPowerGamerBR** [comment]
Everything *seems* to be correct, thanks! 😊

**Comment by MrPowerGamerBR** [comment]
So your reward would be:
`5,3 BRL` (from yesterday) + `42 BRL` (from today) = 47,3 (let's round it to 50 BRL just be a nice round number)

So, if you want to receive your reward, please ping me on Loritta's community server on the chat channel! (and say that you are the guy that made this PR)

**Pull request merged**
