### PR TITLE
Fix some bugs at action commands

### PR DESCRIPTION
**Pull request by SrGaabriel**
Sorry 
image

### CODE REVIEW

**Comment by hechfx** [comment]
You should put the comments in english
image

**Comment by SrGaabriel** [comment]
I didn't write the commands, @MrPowerGamerBR did.

**Comment by hechfx** [comment]
just translate 'em 🤔

**Comment by SrGaabriel** [comment]
Okay, I'll do! 😄

**Comment by SrGaabriel** [comment]
I've tested and all the bugs were fixed and the documentation was translated.

**Comment by SrGaabriel** [comment]
Yes, this one was missing 😅

**Pull request merged**
