### PR TITLE
ShipCommand: Now embed color will change depending on percentage

### PR DESCRIPTION
**Pull request by Lucasmellof**
Related to https://github.com/LorittaBot/Loritta/issues/2345

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
If you could show some screenshots showing off how it looks in Discord (with different ship values), it would be great!

**Comment by Lucasmellof** [comment]
image
I had some problems to run Loritta on my pc, so I tested it on my bot.

**Comment by Lucasmellof** [comment]
image
image
image
image
I fixed my PostgreSQL installation and it worked

**Comment by MrPowerGamerBR** [comment]
Looks good to me!

**Pull request merged**
