### PR TITLE
Add a reminder "snooze" button

### PR DESCRIPTION
**Pull request by Tisawesomeness**
See: Issue #2176 

When a reminder goes off, users can click the :zzz: reaction to be reminded again in 10 minutes.

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
Looks great! The only thing I would change is allowing the user to specify how much time the delay can be.

Example: The 🕙 emoji would snooze for 1 minute, but there could also be a 🆙 emoji (those are just examples I know they suck) that would allow to write how much time the timer should be delayed for (Example: The user clicks the  🆙 emoji, Loritta asks "how much time should I wait until I trigger the reminder again?", then the reminder is updated!)

**Comment by MrPowerGamerBR** [comment]
By the way: I *really* should make it possible to get the user's locale *somewhere*.

**Comment by Tisawesomeness** [comment]
Now, users can click :alarm_clock: to quickly set a reminder for the default time (10 minutes), or click :calendar: to choose how long the delay is.

**Comment by MrPowerGamerBR** [comment]
Awesome! 🌟

**Comment by MrPowerGamerBR** [comment]
I'm not sure, but what if someone writes something that has a `@everyone` in this message? https://github.com/LorittaBot/Loritta/pull/2224/files#diff-5e48ff83230f16c38f6e3ebd864320a472192a1f1f86cb4a6e809a84e0601ea0R129

**Comment by xGabrielDEV** [comment]
Yes, I think you should put the message between the ` character.

**Comment by Tisawesomeness** [comment]
Good catch! Just did some testing and it turns out you can stick a `@everyone` in the date and the bot will ping. `MarkdownUtil.monospace()` should fix that. Alternatively there's `MessageAction.setDefaultMentions()` which can disable `@everyone` by default.

Once the reminder thread has access to the locale, a date format would be better.

**Comment by xGabrielDEV** [comment]
That's perfect! 

I think using codeblocks would be easier, but that way is great too!

**Comment by MrPowerGamerBR** [comment]
I didn't even know that there was a MarkdownUtil class, haha

Looks good, tbh what I would have done is just stripping out mentions by using `.escapeMentions()` (from the TextUtils class) and `.stripCodeMarks()` (also from the TextUtils class)

**Comment by MrPowerGamerBR** [comment]
About getting the user's locale on the thread: The problem is that currently there isn't a *good* way for the user to set their preferred language (currently it is possible to set by using `language` via DMs, but I want to change that because it isn't obvious at all and there isn't a way to unset the user's preferred language)

**Comment by Tisawesomeness** [comment]
You bet I abuse MarkdownUtils every chance I get lol.

**Pull request merged**
