### PR TITLE
@everyone bug

### PR DESCRIPTION
**Pull request by VitorBlog**
maybe that fix it

### CODE REVIEW

**Comment by ArthurProgrammer** [comment]
The same happens with "+baninfo" you should fix that too

**Comment by zLupa** [comment]
> The same happens with "+baninfo" you should fix that too

Baninfo is only for administration, no?

**Comment by ArthurProgrammer** [comment]
> > The same happens with "+baninfo" you should fix that too
> 
> Baninfo is only for moderatores, no?

Sure, but would be nice to fix in this command too

**Comment by VitorBlog** [comment]
For some reason the build fail at RepCommand, i really don't known why...

**Comment by MrPowerGamerBR** [comment]
Fixed in https://github.com/LorittaBot/Loritta/commit/a25ce06f023317c08ae31f7f1a2732a619ff6022

**Pull request closed without merging**
