### PR TITLE
Migrate legacylocale to new

### PR DESCRIPTION
**Pull request by Lucasmellof**
related to https://github.com/LorittaBot/Loritta/pull/2264

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
There seems to be a lot of code conflicts because I also pushed some changes before to my branch

**Comment by Lucasmellof** [comment]
What i should do?

**Comment by MrPowerGamerBR** [comment]
You can try solving the conflicts here (by keeping the changes that are already on my branch): https://github.com/LorittaBot/Loritta/pull/2265/conflicts

Or, if you prefer, you can start from scratch and copy the changes that I didn't do yet

**Comment by MrPowerGamerBR** [comment]
@Lucasmellof I've fixed the merge issues, now it should be OK :3

But if you can, try cleaning up this PR https://github.com/LorittaBot/LorittaLocales/pull/111 because yours has a lot of changes that I also did. So try comparing the strings that are *not* migrated yet (after my changes) and the stuff that's here https://github.com/LorittaBot/Loritta/pull/2265/files (which are your changes that I haven't done yet)

Then, when everything is done, create a new PR on the Locales (or update your already existing PR) and everything should be good to go!

**Pull request closed without merging**
