### PR TITLE
Improve all moderation commands and migrate theirs locales entries.

### LINKED ISSUE #2240: Bug: Lori creates a new muted role if the server language isn't the same as the user's language
If a user has English as their personal language (by using the language command in Loritta's DM), Loritta will make a new role if that user tries to mute someone in a server where the language is Portuguese and therefore the role's name is different. As a result of that, there can be problems with permissions, resulting in the user not actually being muted. This can be seen happening [here](https://canary.discord.com/channels/297732013006389252/297732013006389252/770405572687429671), the user was muted but kept on spamming the chat because the English muted role had permission to do so. 

This isn't that important since it can easily be fixed by changing the role's permissions, but should be considered when making any changes or implementing suggestions to the +mute command.

This issue is further aggravated by not being able to set the personal locale as default, meaning after you set a personal language, there's no way to have Lori just use the server's language.

### PR DESCRIPTION
**Pull request by SrGaabriel**
* Loritta: https://github.com/LorittaBot/Loritta/pull/2243
* Locales: https://github.com/LorittaBot/LorittaLocales/pull/104
Fixes #2240

### CODE REVIEW

**Comment by SrGaabriel** [comment]
Note: Me and @ArthurProgrammer tested all commands and they seem to work fine.

**Review by Nightdavisao — APPROVED** [review]
LGTM

**Comment by SrGaabriel** [comment]
Fixes #2240

**Review by Nightdavisao — APPROVED** [review]

**Comment by SrGaabriel** [comment]
Contributes to https://github.com/LorittaBot/Loritta/issues/2119

**Pull request merged**
